"""
Módulo Skills - Registro y definición de todas las habilidades del juego.
Cada habilidad define su comportamiento, costos y efectos.
"""

# ============================================================
# REGISTRO DE HABILIDADES (HEROES)
# ============================================================
HERO_SKILLS = {

    # --- SEIYA DE PEGASO ---
    "meteor_fist": {
        "id": "meteor_fist",
        "name": "Puño Meteoro de Pegaso",
        "icon": "🌠",
        "description": "3 golpes rápidos contra un enemigo. Cada impacto lleva el fuego del Cosmo.",
        "mp_cost": 0,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 3,
        "power": 0.80,       # % de ATK por golpe
        "armor_pen": 0.0,
        "cooldown": 0,
        "status_effect": None,
        "status_chance": 0,
        "status_duration": 0,
        "element": "light",
        "is_basic": True,
    },
    "rolling_crash": {
        "id": "rolling_crash",
        "name": "Rolling Crash de Pegaso",
        "icon": "💥",
        "description": "Embestida giratoria que aturde al objetivo por 1 turno.",
        "mp_cost": 80,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 1.20,
        "armor_pen": 0.10,
        "cooldown": 2,
        "status_effect": "stun",
        "status_chance": 40,
        "status_duration": 1,
        "element": "light",
        "is_basic": False,
    },
    "ryusei_ken": {
        "id": "ryusei_ken",
        "name": "Ryusei Ken – Lluvia de Meteoros",
        "icon": "☄️",
        "description": "5 golpes distribuidos aleatoriamente entre todos los enemigos vivos.",
        "mp_cost": 120,
        "target_type": "all_enemies_random",
        "effect_type": "damage",
        "hits": 5,
        "power": 0.60,
        "armor_pen": 0.0,
        "cooldown": 3,
        "status_effect": None,
        "status_chance": 0,
        "status_duration": 0,
        "element": "light",
        "is_basic": False,
    },
    "comet_punch": {
        "id": "comet_punch",
        "name": "Puño Cometa de Pegaso",
        "icon": "🌌",
        "description": "Golpe devastador que también otorga un buff de crítico al lanzador.",
        "mp_cost": 160,
        "target_type": "single_enemy",
        "effect_type": "mixed",
        "hits": 1,
        "power": 2.00,
        "armor_pen": 0.15,
        "cooldown": 4,
        "status_effect": "crit_up",
        "status_chance": 100,
        "status_duration": 2,
        "status_target": "self",
        "status_value": 20,
        "element": "light",
        "is_basic": False,
    },

    # --- SHIRYU DEL DRAGÓN ---
    "dragon_fist": {
        "id": "dragon_fist",
        "name": "Puño del Dragón",
        "icon": "🐲",
        "description": "Golpe poderoso con escama de dragón que puede causar sangrado.",
        "mp_cost": 0,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.90,
        "armor_pen": 0.0,
        "cooldown": 0,
        "status_effect": "bleed",
        "status_chance": 35,
        "status_duration": 2,
        "element": "earth",
        "is_basic": True,
    },
    "rozan_rising_dragon": {
        "id": "rozan_rising_dragon",
        "name": "Dragón Ascendente de Rozan",
        "icon": "🌊",
        "description": "La técnica sagrada del Monte Rozan. Ignora el 30% de la DEF enemiga.",
        "mp_cost": 100,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 1.60,
        "armor_pen": 0.30,
        "cooldown": 3,
        "status_effect": "def_down",
        "status_chance": 35,
        "status_duration": 2,
        "status_value": 0.20,
        "element": "earth",
        "is_basic": False,
    },
    "dragon_shield": {
        "id": "dragon_shield",
        "name": "Escudo del Dragón",
        "icon": "🛡️",
        "description": "Crea un escudo para el aliado más débil (o Shiryu si está solo) que absorbe el 25% de su HP máximo.",
        "mp_cost": 90,
        "target_type": "ally_lowest_hp",
        "effect_type": "buff",
        "hits": 0,
        "power": 0,
        "armor_pen": 0.0,
        "cooldown": 3,
        "status_effect": "shield",
        "status_chance": 100,
        "status_duration": 2,
        "shield_pct": 0.25,
        "element": "earth",
        "is_basic": False,
    },
    "excalibur": {
        "id": "excalibur",
        "name": "Excalibur",
        "icon": "⚔️",
        "description": "La espada legendaria de Shiryu. Golpe definitivo que ignora el 50% de la defensa.",
        "mp_cost": 180,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 2.20,
        "armor_pen": 0.50,
        "cooldown": 5,
        "status_effect": None,
        "status_chance": 0,
        "status_duration": 0,
        "element": "earth",
        "is_basic": False,
    },

    # --- HYOGA DEL CISNE ---
    "aurora_freeze": {
        "id": "aurora_freeze",
        "name": "Congelación de la Aurora",
        "icon": "❄️",
        "description": "Lanza cristales de hielo que pueden congelar al objetivo.",
        "mp_cost": 0,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.85,
        "armor_pen": 0.0,
        "cooldown": 0,
        "status_effect": "freeze",
        "status_chance": 30,
        "status_duration": 1,
        "element": "ice",
        "is_basic": True,
    },
    "diamond_dust": {
        "id": "diamond_dust",
        "name": "Polvo de Diamante",
        "icon": "💎",
        "description": "Tormenta de cristales que golpea a todos los enemigos y reduce su velocidad.",
        "mp_cost": 110,
        "target_type": "all_enemies",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.70,
        "armor_pen": 0.0,
        "cooldown": 3,
        "status_effect": "spd_down",
        "status_chance": 25,
        "status_duration": 2,
        "status_value": 0.30,
        "element": "ice",
        "is_basic": False,
    },
    "cold_coffin": {
        "id": "cold_coffin",
        "name": "Ataúd Gélido",
        "icon": "🧊",
        "description": "Encapsula al objetivo en hielo sólido por 2 turnos.",
        "mp_cost": 150,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 1.80,
        "armor_pen": 0.10,
        "cooldown": 4,
        "status_effect": "freeze",
        "status_chance": 60,
        "status_duration": 2,
        "element": "ice",
        "is_basic": False,
    },
    "aurora_execution": {
        "id": "aurora_execution",
        "name": "Ejecución de la Aurora",
        "icon": "🌌",
        "description": "Daño devastador. Si el objetivo está congelado, el daño se duplica.",
        "mp_cost": 200,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 1.50,
        "armor_pen": 0.20,
        "cooldown": 5,
        "bonus_vs_frozen": 2.00,
        "status_effect": "freeze",
        "status_chance": 45,
        "status_duration": 1,
        "element": "ice",
        "is_basic": False,
    },

    # --- SHUN DE ANDRÓMEDA ---
    "nebula_whip": {
        "id": "nebula_whip",
        "name": "Látigo de Nebulosa",
        "icon": "⛓️",
        "description": "Cadenas de nebulosa que atrapan al objetivo, pudiendo inmovilizarlo.",
        "mp_cost": 0,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.75,
        "armor_pen": 0.0,
        "cooldown": 0,
        "status_effect": "bind",
        "status_chance": 25,
        "status_duration": 1,
        "element": "wind",
        "is_basic": True,
    },
    "rolling_defense": {
        "id": "rolling_defense",
        "name": "Defensa Giratoria",
        "icon": "🌀",
        "description": "Crea escudos de nebulosa para todos los aliados que absorben el 20% de su HP máximo.",
        "mp_cost": 120,
        "target_type": "all_allies",
        "effect_type": "buff",
        "hits": 0,
        "power": 0,
        "armor_pen": 0.0,
        "cooldown": 4,
        "status_effect": "shield",
        "status_chance": 100,
        "status_duration": 2,
        "shield_pct": 0.20,
        "element": "wind",
        "is_basic": False,
    },
    "stardust_sand": {
        "id": "stardust_sand",
        "name": "Arena de Polvo Estelar",
        "icon": "✨",
        "description": "Nube de polvo estelar que daña a todos los enemigos y puede dormirlos.",
        "mp_cost": 130,
        "target_type": "all_enemies",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.90,
        "armor_pen": 0.0,
        "cooldown": 3,
        "status_effect": "sleep",
        "status_chance": 35,
        "status_duration": 1,
        "element": "wind",
        "is_basic": False,
    },
    "nebula_storm": {
        "id": "nebula_storm",
        "name": "Tormenta de Nebulosa",
        "icon": "🌪️",
        "description": "Liberación total del Cosmo de Andrómeda. Daño masivo y debilita el ataque del objetivo.",
        "mp_cost": 160,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 1.80,
        "armor_pen": 0.15,
        "cooldown": 4,
        "status_effect": "atk_down",
        "status_chance": 50,
        "status_duration": 2,
        "status_value": 0.30,
        "element": "wind",
        "is_basic": False,
    },

    # --- IKKI DEL FÉNIX ---
    "phoenix_wing": {
        "id": "phoenix_wing",
        "name": "Ala de Fénix",
        "icon": "🦚",
        "description": "Alas llameantes del Fénix que pueden quemar al objetivo.",
        "mp_cost": 0,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.95,
        "armor_pen": 0.0,
        "cooldown": 0,
        "status_effect": "burn",
        "status_chance": 20,
        "status_duration": 2,
        "element": "fire",
        "is_basic": True,
    },
    "phoenix_illusion": {
        "id": "phoenix_illusion",
        "name": "Ilusión del Fénix",
        "icon": "🌀",
        "description": "El objetivo cae en una ilusión y ataca a sus propios aliados por 2 turnos.",
        "mp_cost": 80,
        "target_type": "single_enemy",
        "effect_type": "debuff",
        "hits": 0,
        "power": 0,
        "armor_pen": 0.0,
        "cooldown": 3,
        "status_effect": "confusion",
        "status_chance": 60,
        "status_duration": 2,
        "element": "fire",
        "is_basic": False,
    },
    "fly_phoenix": {
        "id": "fly_phoenix",
        "name": "Vuelo del Fénix",
        "icon": "🔥",
        "description": "El golpe más poderoso del Fénix. No puede ser esquivado.",
        "mp_cost": 140,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 2.00,
        "armor_pen": 0.20,
        "cooldown": 4,
        "bypass_dodge": True,
        "status_effect": "burn",
        "status_chance": 50,
        "status_duration": 2,
        "element": "fire",
        "is_basic": False,
    },
    "phoenix_resurrection": {
        "id": "phoenix_resurrection",
        "name": "Resurrección del Fénix",
        "icon": "✨",
        "description": "Convoca el Cosmo del Fénix para curar al aliado más débil y potenciar el ataque del equipo.",
        "mp_cost": 200,
        "target_type": "ally_lowest_hp",
        "effect_type": "heal",
        "hits": 0,
        "power": 0,
        "heal_pct": 0.40,
        "armor_pen": 0.0,
        "cooldown": 5,
        "status_effect": "atk_up",
        "status_chance": 100,
        "status_duration": 2,
        "status_target": "all_allies",
        "status_value": 0.20,
        "element": "fire",
        "is_basic": False,
    },
}

# ============================================================
# REGISTRO DE HABILIDADES (ENEMIGOS)
# ============================================================
ENEMY_SKILLS = {

    # --- CERBERO ---
    "triple_bite": {
        "id": "triple_bite",
        "name": "Triple Mordida Infernal",
        "icon": "🦷",
        "description": "Las tres cabezas de Cerbero atacan simultáneamente al mismo objetivo.",
        "mp_cost": 0,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 3,
        "power": 0.80,
        "armor_pen": 0.0,
        "cooldown": 0,
        "status_effect": None,
        "status_chance": 0,
        "status_duration": 0,
        "element": "dark",
        "is_basic": True,
    },
    "hellfire_breath": {
        "id": "hellfire_breath",
        "name": "Aliento del Infierno",
        "icon": "🔥",
        "description": "Llamas del inframundo que queman a todos los héroes.",
        "mp_cost": 100,
        "target_type": "all_enemies",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.90,
        "armor_pen": 0.0,
        "cooldown": 3,
        "status_effect": "burn",
        "status_chance": 30,
        "status_duration": 2,
        "element": "dark",
        "is_basic": False,
    },
    "petrification_gaze": {
        "id": "petrification_gaze",
        "name": "Mirada Petrificante",
        "icon": "👁️",
        "description": "La mirada de Cerbero paraliza de miedo al objetivo por 2 turnos.",
        "mp_cost": 120,
        "target_type": "single_enemy",
        "effect_type": "debuff",
        "hits": 1,
        "power": 0.60,
        "armor_pen": 0.0,
        "cooldown": 4,
        "status_effect": "petrify",
        "status_chance": 50,
        "status_duration": 2,
        "element": "dark",
        "is_basic": False,
    },

    # --- MEDUSA ---
    "snake_lash": {
        "id": "snake_lash",
        "name": "Latigazo de Serpiente",
        "icon": "🐍",
        "description": "Ataque con cabellos de serpiente que causa sangrado.",
        "mp_cost": 0,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.85,
        "armor_pen": 0.0,
        "cooldown": 0,
        "status_effect": "bleed",
        "status_chance": 40,
        "status_duration": 2,
        "element": "dark",
        "is_basic": True,
    },
    "cursed_gaze": {
        "id": "cursed_gaze",
        "name": "Mirada Maldita",
        "icon": "🧿",
        "description": "La maldición de Medusa reduce la defensa del objetivo un 35%.",
        "mp_cost": 90,
        "target_type": "single_enemy",
        "effect_type": "debuff",
        "hits": 0,
        "power": 0,
        "armor_pen": 0.0,
        "cooldown": 3,
        "status_effect": "def_down",
        "status_chance": 80,
        "status_duration": 2,
        "status_value": 0.35,
        "element": "dark",
        "is_basic": False,
    },
    "mass_petrification": {
        "id": "mass_petrification",
        "name": "Petrificación Masiva",
        "icon": "🗿",
        "description": "La mirada de Medusa intenta petrificar a todos los héroes.",
        "mp_cost": 150,
        "target_type": "all_enemies",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.70,
        "armor_pen": 0.0,
        "cooldown": 4,
        "status_effect": "petrify",
        "status_chance": 30,
        "status_duration": 2,
        "element": "dark",
        "is_basic": False,
    },

    # --- QUIMERA ---
    "lion_pounce": {
        "id": "lion_pounce",
        "name": "Zarpazo del León",
        "icon": "🦁",
        "description": "Salto feroz con garras que puede aturdir al objetivo.",
        "mp_cost": 0,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 1.00,
        "armor_pen": 0.0,
        "cooldown": 0,
        "status_effect": "stun",
        "status_chance": 30,
        "status_duration": 1,
        "element": "fire",
        "is_basic": True,
    },
    "fire_breath": {
        "id": "fire_breath",
        "name": "Aliento de Fuego",
        "icon": "🌋",
        "description": "Quema a todos los héroes con fuego ancestral.",
        "mp_cost": 100,
        "target_type": "all_enemies",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.80,
        "armor_pen": 0.0,
        "cooldown": 3,
        "status_effect": "burn",
        "status_chance": 25,
        "status_duration": 2,
        "element": "fire",
        "is_basic": False,
    },
    "goat_ram": {
        "id": "goat_ram",
        "name": "Embestida de la Cabra",
        "icon": "🐐",
        "description": "Carga imparable que ignora el 40% de la defensa del objetivo.",
        "mp_cost": 130,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 1.80,
        "armor_pen": 0.40,
        "cooldown": 4,
        "status_effect": None,
        "status_chance": 0,
        "status_duration": 0,
        "element": "fire",
        "is_basic": False,
    },

    # --- ESPECTRO SOMBRÍO ---
    "shadow_strike": {
        "id": "shadow_strike",
        "name": "Golpe en la Sombra",
        "icon": "🌑",
        "description": "Ataque desde las sombras con alta probabilidad de crítico.",
        "mp_cost": 0,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.90,
        "armor_pen": 0.0,
        "cooldown": 0,
        "status_effect": "crit_up",
        "status_chance": 100,
        "status_duration": 1,
        "status_target": "self",
        "status_value": 40,
        "element": "dark",
        "is_basic": True,
    },
    "soul_drain": {
        "id": "soul_drain",
        "name": "Drenaje de Alma",
        "icon": "💜",
        "description": "Roba el alma (MP) del objetivo para fortalecerse.",
        "mp_cost": 60,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.80,
        "armor_pen": 0.0,
        "cooldown": 2,
        "status_effect": "mp_drain",
        "status_chance": 100,
        "status_duration": 1,
        "mp_drain_amount": 80,
        "element": "dark",
        "is_basic": False,
    },
    "death_mark": {
        "id": "death_mark",
        "name": "Marca de la Muerte",
        "icon": "💀",
        "description": "Marca al objetivo con la muerte. El próximo golpe que reciba causará el doble de daño.",
        "mp_cost": 120,
        "target_type": "single_enemy",
        "effect_type": "debuff",
        "hits": 0,
        "power": 0,
        "armor_pen": 0.0,
        "cooldown": 4,
        "status_effect": "death_mark",
        "status_chance": 85,
        "status_duration": 3,
        "element": "dark",
        "is_basic": False,
    },

    # --- MINOTAURO INFERNAL ---
    "labyrinth_rage": {
        "id": "labyrinth_rage",
        "name": "Furia del Laberinto",
        "icon": "🪓",
        "description": "Golpe devastador con el hacha del laberinto.",
        "mp_cost": 0,
        "target_type": "single_enemy",
        "effect_type": "damage",
        "hits": 1,
        "power": 1.20,
        "armor_pen": 0.10,
        "cooldown": 0,
        "status_effect": "stun",
        "status_chance": 20,
        "status_duration": 1,
        "element": "earth",
        "is_basic": True,
    },
    "ground_slam": {
        "id": "ground_slam",
        "name": "Golpe Sísmico",
        "icon": "🌍",
        "description": "Golpea el suelo creando una onda expansiva que daña y ralentiza a todos.",
        "mp_cost": 110,
        "target_type": "all_enemies",
        "effect_type": "damage",
        "hits": 1,
        "power": 0.85,
        "armor_pen": 0.0,
        "cooldown": 3,
        "status_effect": "spd_down",
        "status_chance": 20,
        "status_duration": 2,
        "status_value": 0.25,
        "element": "earth",
        "is_basic": False,
    },
    "blood_frenzy": {
        "id": "blood_frenzy",
        "name": "Frenesí Sangriento",
        "icon": "🩸",
        "description": "Se baña en su propia sangre para ganar una furia devastadora. Solo usable con HP < 50%.",
        "mp_cost": 80,
        "target_type": "self",
        "effect_type": "buff",
        "hits": 0,
        "power": 0,
        "armor_pen": 0.0,
        "cooldown": 6,
        "status_effect": "atk_up",
        "status_chance": 100,
        "status_duration": 3,
        "status_target": "self",
        "status_value": 0.40,
        "requires_hp_below": 50,
        "element": "earth",
        "is_basic": False,
    },
}

# Registro unificado
ALL_SKILLS = {**HERO_SKILLS, **ENEMY_SKILLS}


def get_skill(skill_id: str) -> dict:
    """Obtiene los datos de una habilidad por su ID."""
    return ALL_SKILLS.get(skill_id, None)


def get_skills_for(skill_ids: list) -> list:
    """Retorna lista de datos de habilidades dado una lista de IDs."""
    return [ALL_SKILLS[sid] for sid in skill_ids if sid in ALL_SKILLS]
